ДЗ 1
LadaKuzmina/2024-2-VK-EDU-Frontend-L-Kuzmina pull request #1
Opened 2024-09-24 14:24 UTC by LadaKuzmina

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:
* Реализовала функции convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
* Написала тесты в файле convertBytesToHuman.test.js для функции convertBytesToHuman.js

2024-09-24 14:50 UTC, kgrechin approved these changes

2024-09-24 14:50 UTC, kgrechin commented on convertBytesToHuman.js
> +  while (bytes >= 1024){
а если индекс выйдет за границы unitsOfMeasurement?

2024-09-24 14:50 UTC, kgrechin commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman('abc')).toBe(false);
добавить тест на NaN

2024-09-24 14:50 UTC, kgrechin commented on nonUniqueElements.js
> +  let dict = new Map();
почему именно Map выбрала, а не {}?

добавить проверку входного значения

доп. задание:
написать функцию декоратор,  которая замеряет время выполнения переданной в нее функции.
с помощью функции-декоратора замерять время выполнения функции nonUniqueElements с Map и с {}.
сделать выводы,  что быстрее

2024-09-24 14:50 UTC, kgrechin commented on correctSentence.js
> +  return `${text.charAt(0).toUpperCase()}${text.slice(1)}${text.charAt(text.length -1) === '.' ? '' : '.'}`;
добавить проверку входного значения

доп. задание:
входящая строка может содержать HTML escape codes, нужно все  их заменить на нормальные символы

пример :`&quot;hello&amp; welcome to &lt;course&gt;&quot; -> "Hello & welcome to <course>"` 

добавить пару тестов от себя
логика с заглавной первой буквой и точкой в конце остается

2024-09-24 14:52 UTC, kgrechin requested changes

2024-09-24 14:52 UTC, kgrechin commented on convertBytesToHuman.js
> +  const unitsOfMeasurement = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
а если индекс выйдет за границы unitsOfMeasurement?

2024-09-26 05:30 UTC, kgrechin commented
@LadaKuzmina, ждем фиксов)

2024-09-26 17:42 UTC, LadaKuzmina commented on nonUniqueElements.js
> +  let dict = new Map();
Я хотела именно словарь, а не просто объект, поэтому выбрала Map. Хочу сделать еще дополнительные задания, но произошла дезинформация по дедлайнам. На сайте указана дата 26 сентября, в презентации и на паре говорили - 30 сентября. Также говорили, что на дз дается две недели, а прошло всего 10. Подскажи, пожалуйста, я еще успеваю сделать доп задания или уже нет?

2024-09-26 17:43 UTC, LadaKuzmina commented on convertBytesToHuman.js
> +  const unitsOfMeasurement = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
будет больно( 
исправила: сделала проверку

2024-09-26 18:04 UTC, kgrechin commented on nonUniqueElements.js
> +  let dict = new Map();
привет) да, первую версию ты загрузила до делайна, так что все ок, дедлайн для загрузки с получением максимального количества баллов 30 сентября, Мартин должен был приложить табличку с датами

2024-09-29 14:28 UTC, LadaKuzmina commented on nonUniqueElements.js
> +  let dict = new Map();
Привет! я сделала доп задания. Подскажи, пожалуйста, загрузка - это создание пулл реквеста или влитие в мастер?

2024-09-30 02:51 UTC, kgrechin commented on nonUniqueElements.js
> +  let dict = new Map();
привет) создание пулл реквеста (не пустого). должна быть логика дз

2024-09-30 02:53 UTC, kgrechin approved these changes
@LadaKuzmina, в correctSentence немного громоздко по логике получилось, но решение рабочее, переходи к следующему дз)

@HaseProgram, @martinkomitsky, от меня аппрув

2024-10-01 18:46 UTC, merged

2024-10-01 18:46 UTC, martinkomitsky commented
12!