Exam
LadaKuzmina/2024-2-VK-EDU-Frontend-L-Kuzmina pull request #12
Opened 2024-12-23 18:12 UTC by LadaKuzmina

# Экзамен

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:
* В корневой папке репозитория создать базовое приложение exam с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
* Сверстать 2 страницы и необходимые компоненты
* Использовать стили. Дизайн должен быть похожим на макет
* Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
* Реализовать перевод с неизвестного языка (автоопределитель из API)
* Сохранять историю переводов в localStorage
* Использовать Redux
* Использовать React-router для перехода между страницами
* Задеплоить решение, используя GitHub Actions
* Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-29 21:08 UTC, martinkomitsky commented
Предварительная оценка: 36

2025-01-03 00:43 UTC, HaseProgram requested changes
Привет! По коду замечаний нет, хорошо сделано.
Но есть один баг - история не восстанавливается из локал стораджа. Поправь, пожалуйста, и будет 46

2025-01-07 19:44 UTC, LadaKuzmina commented
@HaseProgram Привет, я пофиксила баг. Вот до и после:
До:
https://github.com/user-attachments/assets/2207230a-7c8a-4209-bb6d-7625bc141d89

После:

https://github.com/user-attachments/assets/65c16675-0f0b-460c-8991-dd3cb9e3f94e

2025-01-12 18:46 UTC, HaseProgram approved these changes
Привет, супер, теперь максимум :))

2025-01-12 18:46 UTC, merged