homework_2
LadaKuzmina/2024-2-VK-EDU-Frontend-L-Kuzmina pull request #2
Opened 2024-10-02 18:16 UTC by LadaKuzmina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:
* Стилизовала форму отправки сообщений
* Реализовала функционал отправки сообщений
* Сделала деплой

2024-10-03 06:24 UTC, kgrechin commented
<img width="1680" alt="Снимок экрана 2024-10-03 в 09 24 17" src="https://github.com/user-attachments/assets/c43da9de-96f4-4cc2-bdcf-b78cbe051edb">

что-то пошло не так(

2024-10-03 06:28 UTC, kgrechin requested changes
@LadaKuzmina, жду задания соответсвующего макетам и фиксов по комментариям)

2024-10-03 06:28 UTC, kgrechin commented on simple-chat/build/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
добавить папку build в gitignore

2024-10-03 06:28 UTC, kgrechin commented on simple-chat/src/index.html
> +    <div id="list-message"></div>
нам нужна верстка по макетам, а не просто инпут и добавление сообщений))

смотри макеты к заданию, должен быть хедер, мейн, футер и респонсивная верстка

2024-10-03 06:28 UTC, kgrechin commented on simple-chat/src/index.js
> +    listMessage.innerHTML = myMessage.map(message => `
сюда сейчас можно вставить любую верстку из инпута, лучше использовать innerText для вставки внешних данных

2024-10-03 06:28 UTC, kgrechin commented on simple-chat/src/index.js
> +    result = listMessage.innerHTML = myMessage.map(message => `
innerText

2024-10-03 13:13 UTC, LadaKuzmina commented on simple-chat/src/index.html
> +    <div id="list-message"></div>
В задании написано: "Стилизовать форму отправки сообщений (в меру возможности)". В моем понимании это стилизовать инпут и отправку сообщений от моего лица. Нужно реализовать весь макет?

2024-10-03 15:15 UTC, LadaKuzmina commented on simple-chat/src/index.html
> +    <div id="list-message"></div>
> респонсивная верстка
лекция называется "основы js", а по дз нужно сверстать полный мессенджер, даже с адаптивом. как так получилось? и почему ничего не сказано об этом в самом домашнем задании?

2024-10-03 15:28 UTC, LadaKuzmina commented on simple-chat/src/index.html
> +    <div id="list-message"></div>
судя по макетам, должен быть и получатель сообщений, чтобы были слева и справа.  а для этого нужен бэкенд. в курсе говорили, что бэкенд уже готовый, но я его не нашла в данном дз. странно, что не всех учеников просят сделать сообщения с обоих сторон

2024-10-04 06:33 UTC, kgrechin commented on simple-chat/src/index.html
> +    <div id="list-message"></div>
@LadaKuzmina, На занятии рассматривались основы HTML, CSS, JS

Нужно сделать только экран чата - хедер с иконками, мейн с сообщениями и футер с инпутом
Если дз вызывает сложности, пиши мне в лс в телеграм, помогу разобраться

2024-10-06 17:44 UTC, LadaKuzmina commented on simple-chat/build/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
добавила и сделала push force, но папка из пр не удалилась

2024-10-06 17:46 UTC, LadaKuzmina commented on simple-chat/src/index.js
> +    listMessage.innerHTML = myMessage.map(message => `
не поняла, в чем проблема?(
я использую innerHTML, так как у меня дальше идет верстка, а не просто текст

2024-10-07 16:20 UTC, LadaKuzmina commented on simple-chat/src/index.js
> +    result = listMessage.innerHTML = myMessage.map(message => `
@kgrechin привет! я исправила, посмотри, пожалуйста

2024-10-08 05:05 UTC, kgrechin commented on simple-chat/src/index.js
> +    listMessage.innerHTML = myMessage.map(message => `
через инпут можно вставить любую верстку в innerHTML, например <div style="color: red">text</div> или даже <script src="./inject.js" />

молодец, что исправила

2024-10-08 05:05 UTC, kgrechin commented on simple-chat/build/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
вроде как исчезла)

2024-10-08 05:12 UTC, kgrechin requested changes
@LadaKuzmina, осталась только верстка)

2024-10-08 05:12 UTC, kgrechin commented on simple-chat/src/index.html
> +    <header class="header">
верстке чет плоховато))

накидал тут небольшой пример для тебя, как я вижу вертску данной страницы:

```
<template>
  <div class="wrapper">
    <div class="header"></div>

    <div class="main">
      <div class="messages">
        <div class="message">Message1</div>
        <div class="message">Message2</div>
        <div class="message">Message3</div>
        <div class="message">Message4</div>
        <div class="message">Message5</div>
        <div class="message">Message6</div>
        <div class="message">Message7</div>
      </div>
    </div>

    <div class="footer"></div>
  </div>
</template>
```

```
<style>
html, body, div[id="app"] {
  height: 100%;
  margin: 0;
}

.wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.header, .footer {
  height: 60px;
  background-color: black;
}

.main {
  flex: 1;
  display: flex;
  flex-direction: column-reverse;
  overflow-y: auto;
}

.messages {
  display: flex;
  gap: 10px;
  flex-direction: column;
}

.message {
  width: 400px;
  height: 100px;
  border: 1px solid black;
}
</style>
```

также в хедере элементы выглядят странно, отступы, положения, особенно при ресайзе) нужно их привести в более органичное состояние

2024-10-08 16:34 UTC, LadaKuzmina commented on simple-chat/src/index.html
> +    <header class="header">
а в чем плоха моя вёрстка? я использую специальные теги для семантики, чтобы браузеры быстрее находили нужную информацию. также это важно для доступности, так как скринридеры читают именно по тегам, а предлагаемая вёрстка болеет диватозом.

органичное состояние - это какое? макет представлен только в виде картинки и для одного устройства. я вижу положение, отступы элементов таким образом. подскажи, пожалуйста, где конкретнее поменять и почему

2024-10-10 07:02 UTC, kgrechin commented on simple-chat/src/index.html
> +    <header class="header">
@LadaKuzmina 

https://github.com/user-attachments/assets/9927fae6-a784-44f0-8cf9-e47595d2fd5b

нужно поправить отображение многострочных сообщений,  сейчас это одна длинная строка, нужно чтобы текст переносился (желательно конечно, чтобы и в инпуте текст вводился построчно,  а не в одну длинную строку)

нужно поправить скролл, скролл должен быть только в блоке сообщений, инпут и хедер - всегда видны пользователю.

семантические теги правильно) данный пример оставил,  как вариант расположения элементов на странице, без скролла всей страницы,  а с фиксированными хедером и инпутом и скроллящимся блоком сообщений, теги можно заменить на семантические

2024-10-13 08:00 UTC, LadaKuzmina commented on simple-chat/src/index.html
> +    <header class="header">
@kgrechin Привет, исправила. Посмотри, пожалуйста, а то я не могу приступить к следующим дз

2024-10-13 09:42 UTC, kgrechin approved these changes
@LadaKuzmina, подлил небольшие фиксы, оставил комментарии в коде, посмотри пожалуйста

2024-10-13 09:44 UTC, kgrechin commented
@HaseProgram , @martinkomitsky , от меня аппрув

2024-10-13 17:34 UTC, HaseProgram approved these changes
12!

2024-10-13 17:34 UTC, merged