Dz5
LadaKuzmina/2024-2-VK-EDU-Frontend-L-Kuzmina pull request #6
Opened 2024-10-23 18:06 UTC by LadaKuzmina

# Домашнее задание № 5

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:
* Переписала всё на React
*
*

2024-10-23 18:09 UTC, LadaKuzmina commented
@kgrechin Привет! У меня проблемы с 5 дз. Сломался билд в PR, хотя локально всё хорошо. Не подключаются в некоторых файлах стили css. И почему-то сообщение в чате при отправке отображается не сразу, а только после обновления страницы. Подскажи, пожалуйста🙏

2024-10-26 08:04 UTC, kgrechin requested changes

2024-10-26 08:04 UTC, kgrechin commented on react-chat/src/components/header-chat/HeaderChat.css
> +/*  .time-interlocutor {*/
закоменнченный код если не используется лучше сразу удалить

2024-10-26 08:04 UTC, kgrechin commented on react-chat/src/components/chat-mocks/chat-mocks.js
> +    },
это лучше хранить не в components - можно завести папку mocks в корне либо api/mocks, либо ls/mocks

2024-10-26 08:05 UTC, kgrechin commented
@LadaKuzmina, пофиксил билд, деплой и реактивность при сохранении сообщения

Также нужно настроить структуру проекта, пока что компонентов (это можно сделать уже в следующем дз):

Давай разграничим компоненты на тупые и с логикой, допусти папка components - папка с тупыми компонентами, без логики работы со сторами, LS, апи и тд:

components/Button
components/Header
components/Form
components/Textarea
...

Папка modules - папка с компонентами с логикой:
modules/chat/ChatItem.jsx, ChatList.jsx...
modules/message/MessageItem.jsx, MessageList.jsx...

два коммента, которые отписал, надо пофиксить сейчас)

2024-10-28 16:31 UTC, LadaKuzmina commented
@kgrechin Привет! Спасибо за объяснение🙏 Посмотри, пожалуйста, правки. Структуру проекта поправлю со следующим дз

2024-10-31 06:10 UTC, kgrechin approved these changes
@LadaKuzmina огонь

2024-10-31 06:11 UTC, kgrechin commented
12!

2024-10-31 06:11 UTC, merged