homework_7
LadaKuzmina/2024-2-VK-EDU-Frontend-L-Kuzmina pull request #8
Opened 2024-11-21 18:02 UTC by LadaKuzmina

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:
* Добавила страницу авторизации и регистрации
*
*

2024-11-23 12:08 UTC, kgrechin requested changes
@LadaKuzmina, давай будем делать аккуратно по этапам:

1 этап: авторизация (пока что без регистрации):

- сверстать страничку авторизации (есть)
- добавить ReactContext для авторизационных данных:

чтобы на уровне всего проекта были доступны access, refresh токены и данные текущего юзера

все это также сохраняем в LocalStorage (данные юзера не обязательно)

логика следующая:

пользователь заходит на страницу авторизации, вводит логин и пароль, получает access, refresh токены, также сразу же запрашиваем его данные по user/current/ и все сохраняем в contexte  и LocalStorage, после чего перекидываем его на страницу чатов.

а урл для авторизации после авторизации должен быть недоступен, проверяем это по наличию access и refresh токена, если они есть то данный урл запрещен для пользователя, можно сделать компонент прослойку типа AuthManager в котором будет проверяться если ли токены, если есть то будет один набор Routes иначе другой

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/api/apiService.js
> +const API_BASE_URL = 'https://vkedu-fullstack-div2.ru/api';
можно разбить на разные файлы users.js/messages.js/chats.js

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/api/apiService.js
> +const API_BASE_URL = 'https://vkedu-fullstack-div2.ru/api';
из названий лучше убрать toBackend)

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/pages/AuthPage.jsx
> +    const [tokens, setTokens] = useState(null);
для токенов нужно будет написать ReactContext

в котором начальный стейт получаем из localStorage
и есть возможность засетить стейт и сразу же в localStorage

здесь после успешной авторизации будем делать setAuthData (пример имени метода в контексте)

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/pages/ChatPage.jsx
> +        const setupCentrifugo = async () => {
давай для начала воспользуемся просто поллингом) центрифугу успеется прикрутить

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/pages/ChatPage.jsx
> +        const setupCentrifugo = async () => {
чтобы пока что себе лишних проблем не создавать)

2024-11-23 12:08 UTC, kgrechin commented on react-chat/src/pages/RegisterPage.jsx
> +    const handleChange = (e) => {
поле успешной регистрации перекидываем пользователя на страницу авторизации

2024-11-28 04:55 UTC, kgrechin requested changes
@LadaKuzmina, класс

по 1 пункту осталось только сделать:

когда юзер зашел, то ему недоступны страница AUTH и REGISTER

можно сделать что-то подобное:

```
// AuthManager.jsx - в корне проекта
function AuthManager () {
    const { authData } = useContext(AuthContext);

    return authData.accessToken
        ? <App/>
        : (
            <HashRouter>
                <Routes>
                    <Route path="/register" element={<RegisterPage />} />
                    <Route path="/auth" element={<AuthPage />} />
                </Routes>
            </HashRouter>
        )
}

// App.jsx
function App() {
    return (
        <HashRouter>
            <Routes>
                <Route
                    path="/"
                    element={<ChatsPage />}
                />
                <Route
                    path="/chat/:id"
                    element={<ChatPage />}
                />
                <Route
                    path="/edit"
                    element={<ProfilePage />}
                />
            </Routes>
        </HashRouter>
    );
}

// index.jsx
const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(
    <ScritMode>
        <AuthProvider>
            <AuthManager />
        </AuthProvider>
    </ScritMode>
);
```

AuthManager - можно перенести в корень проекта (либо в папку managers/auth/ в корне), AuthContext в папку contexts/auth в корень, не в api

App.jsx и index.jsx также в корне проекта

2024-11-28 17:03 UTC, LadaKuzmina commented
Я не могу вынести в корень проекта файлы App, index и manager, из-за ошибки
ERROR in ./src/index.js 8:0-50
Module not found: Error: You attempted to import ../context/AuthContext which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

2024-11-29 06:26 UTC, kgrechin commented
> Я не могу вынести в корень проекта файлы App, index и manager, из-за ошибки ERROR in ./src/index.js 8:0-50 Module not found: Error: You attempted to import ../context/AuthContext which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.

соре, я имел ввиду /src/

2024-11-29 06:46 UTC, kgrechin requested changes
@LadaKuzmina, немного пофиксил, добавил простейшее решение с переходом по ненужным роутам

в целом 1 этап - готов

переходим ко второму - страница всех чатов:
- нужно добавить запрос за чатами (пока что можно за всеми, без query)
- при переходе на страницу всех чатов запрашиваем и отображаем все чаты юзера, которые получили

2024-12-06 16:40 UTC, kgrechin requested changes

2024-12-06 16:40 UTC, kgrechin commented on react-chat/src/pages/ChatsPage.jsx
> +                const response = await fetch('/api/chats/', {
сейчас не работает - это будет фетч по текущему домену, нужно напрямую ходить в деплой, прокси можно не настраивать

2024-12-06 16:41 UTC, kgrechin commented on react-chat/src/pages/ChatsPage.jsx
> +                const response = await fetch('/api/chats/', {
у тебя вроде в axios настроен baseUrl, тут видимо забыла изменить на axios

2024-12-07 14:51 UTC, LadaKuzmina commented on react-chat/src/pages/ChatsPage.jsx
> +                const response = await fetch('/api/chats/', {
привет! я исправила 2 этап и сделала 3. посмотри, пожалуйста. там есть момент с отправкой сообщения от моего лица. сообщения от моего лица отправляются как от лица собеседника(на белом фоне и с левой стороны). я не разобралась, норм это или нет...

2024-12-08 11:13 UTC, kgrechin commented on react-chat/src/pages/ChatsPage.jsx
> +                const response = await fetch('/api/chats/', {
привет) вроде как все хорошо, единственное, свои сообщения справа, сообщения собеседника - слева, и сообщения, которые отправляет сам юзер можно сразу показывать, а не ждать пока интервал сработает на получение новых сообщений

2024-12-08 11:14 UTC, kgrechin approved these changes
7 баллов

2024-12-08 11:15 UTC, merged